language: java
jdk:
  - openjdk11

sudo: false

cache:
  directories:
    - $HOME/.m2
dist: focal

addons:
  sonarcloud:
    organization: "ripper2hl"
    token:
      secure: "ALhLKY7SoC0cb3BTRJfCRqFpVBdx2hR5M6KBw3pmNUMbN2v43ACQWBGzmqvOATsSx+26zpno6lO7XIcZtTrYBgIGLM/LdIJ6Jw2bHD7ZuNMKuIo8NHRPTgg1OR9j1broyDzpaBIs8lrpGPF0aA89G0Kid1euCz03DpMiXL8bgUmeQWuef85uLV0qDdVou53sAveP7lXblr0j1ZDrwi0gimJ4D/7sMmoEuP2nUcCMqoT8CMPpmA1nq2ueZ5yLiAMY8Ovl/XpbyOIwmm4fFQOwxer++nvp5vmqom4tnJYc+s6o3hfFSgQj64tg2c7b5US62ffbNTuk3UU0CPdErnnL3O3dAUUlUNi9r1UKlg233iZ0rLTPgfMzHPScXrRCjT2s6fcymUwo5snc/S4M7WtyDRR6xxcumY0h2bPnPEOV6Mia2Jpi9TE9laKakMy/oQ4DcBUYI1QT5wRhiQGUvu4WxzZjEfu2Kv5yoxzqxTmxofY2mUUxFjo+Yb5/RRJSZ1FSSUXh0BNsJeoeJf6aoE3XZJ/oY4IKZ/Ja1vz0BnhdW3QTOEYdJT03kPYrREQgw2NhShMM7ivT6Yn8jsh+3ngeDlKukbiAOkS5oWRVyy82foS/tdfSzAm+xK+2uUj3NTAZcCm7KZR5iS3UZhOXgPkjpHiMqq7WOGCaev0DMHkw5yw=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ripper2hl_sepomex